### ISSUE TITLE
Clarification on docs for JSON.ARRAPPEND

### ISSUE THREAD

**Issue by sertugkaya** [upstash/docs#131]
Path: /oss/sdks/py/redis/commands/json/arrappend

Redis [JSON.ARRAPPEND docs](https://redis.io/commands/json.arrappend/) mention that "To specify a string as an array value to append, wrap the quoted string with an additional set of single quotes. Example: '"silver"'."

One of our users had trouble noticing that in our docs, mentioning this gotcha would help

**Comment by ogzhanolguncu** [comment]
Fixed here https://github.com/upstash/docs/pull/146.
