### ISSUE TITLE
Issue on docs for Rate Limit Analytics

### ISSUE THREAD

**Issue by sertugkaya** [upstash/docs#135]
Path: /oss/sdks/ts/ratelimit/analytics

There's a broken image link in the page
<img width="772" alt="Screenshot 2024-04-03 at 11 56 35" src="https://github.com/upstash/docs/assets/3787862/6b8d4f66-743e-4299-8f8f-4c5d4bdd043f">

**Comment by CahidArda** [comment]
image is originally from here https://github.com/upstash/ratelimit/blob/main/.github/img/dashboard.png

shall we simply use it from github in our docs?

**Comment by ogzhanolguncu** [comment]
Fixed here https://github.com/upstash/docs/pull/144.
