### ISSUE TITLE
Free Tier -meaning of Max 10.000 requests per day.

### ISSUE THREAD

**Issue by DimensionZer0** [upstash/docs#175]
what is meaning of Max 10.000 requests per day. How many people can you in free version

**Comment by CahidArda** [comment]
Hi @DimensionZer0,

It means that you can only make 10.000 requests to your Redis each day.

Can you elaborate more on what you mean by "How many people"?

**Comment by CahidArda** [comment]
We are closing this issue, feel free to reach out if you have more questions!
