### ISSUE TITLE
Redis 6.2 will be EOL in August 2024

### ISSUE THREAD

**Issue by pboling** [upstash/docs#183]
Path: /redis/overall/rediscompatibility

Will this be addressed in the Docs?  How does Upstash plan to handle this?  What do we need to do to prepare?  Will we be able to provision new instances on newer versions of Redis?

Docs:
https://upstash.com/docs/redis/overall/rediscompatibility

Support Matrix:
https://redis.io/docs/latest/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54/#supported-platforms

**Comment by mdumandag** [comment]
Upstash Redis is a Redis API compatible implementation written from scratch, so we do not use any of the Redis source code. 

Therefore, EOL of Redis 6.2 will not affect us in any way, you will be able to use our product after that date without any change required in your or our side.

**Comment by pboling** [comment]
Seems like it will likely be the case that the client protocol6.2 will go EOL at the same time, meaning that clients may drop support for 6.2, which is what I understand Upstash uses.  Is that not a concern?  And if not, what makes it not so?

**Comment by mdumandag** [comment]
Redis protocol is not really tied to any Redis version, we support both RESP2 and RESP3 so, all the existing clients will continue to work https://redis.io/docs/latest/develop/reference/protocol-spec/

**Comment by mdumandag** [comment]
BTW, we say that we are compatible with Redis 6.2 because we support most of the commands in Redis 6.2. We do support lots of commands/new command arguments from the Redis 7 series as well, but not all of them yet

**Comment by pboling** [comment]
Thanks for explaining!!  Seeing the number 6.2 with the increasing awareness of an EOL date associated with that number may cause alarm among your customers who don't understand all this nuance.  Perhaps some of this can be summarized in a footnote where 6.2 is mentioned.
