### ISSUE TITLE
Would be great to have a nextjs v13 update to /qstash/quickstarts/vercel-nextjs

### ISSUE THREAD

**Issue by moorage** [upstash/docs#21]
Path: /qstash/quickstarts/vercel-nextjs

Would be nice to use the /app/api/qstash/route.ts format with edge enabled!  Perhaps more ideally would be with edge middleware.

**Comment by chronark** [comment]
Yes 💯 
working on that right now

**Comment by chronark** [comment]
https://upstash.com/docs/qstash/quickstarts/vercel-nextjs
