### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by gerhardcit** [upstash/docs#69]
Path: /redis/quickstarts/fly

Add notes and explanation about availability of the redis url on local development for testing.
It seems that the redis connection given by `fly redis create` is not available to connect to locally.

It seems some kind of tunnel is the only way to connect with `fly redis connect`

**Comment by karan-joshi-1** [comment]
Can I work on this issue @gerhardcit

**Comment by ytkimirti** [comment]
Closing as fixed in #85, thanks for your contributon @karan-joshi-1 🙏

**Comment by karan-joshi-1** [comment]
@ytkimirti really excited to work with you guys on some core stuff. Sent you a email regarding this . Hope you can help.
